Move runtime packages into setup.py
This should fix the following error, which wasn't happening locally
but was blocking release on PyPi via GitHub Actions [^1]:

    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/default.txt'

Locating package dependencies in setup.py is more conventional, while
test dependencies are more "of the project", so it makes sense for
them to remain in individual requirements files.

[^1]: https://github.com/benthorner/snsary/actions/runs/4156426382/jobs/7190208643