Update docs to remove caveat for BigQueryOutput
This is not the case since [^1].

The latest version of GRPCIO - 1.47.0 still has the specified issue:

    ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/ben/.local/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-arm-linux-gnueabihf.so)

Pinning below 1.45.0 is therefore still necessary. Annoyingly on a
Mac M2 chip the problem is reversed and a forced reinstall of the
latest version is required to avoid import errors later on:

    ../../.pyenv/versions/3.10.6/envs/snsary/lib/python3.10/site-packages/grpc/__init__.py:22: in <module>
        from grpc import _compression
    ../../.pyenv/versions/3.10.6/envs/snsary/lib/python3.10/site-packages/grpc/_compression.py:15: in <module>
        from grpc._cython import cygrpc
    E   ImportError: dlopen(/Users/ben/.pyenv/versions/3.10.6/envs/snsary/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/Users/ben/.pyenv/versions/3.10.6/envs/snsary/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

[^1]: 309e7d00755aafbcf19cced7371ba60dfe1573a5